name: Build iOS App

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: List files for debug
        run: ls -R

      - name: Install Cocoapods
        run: |
          if [ -f "iosApp/Podfile" ]; then
            cd iosApp
            pod install
          else
            echo "Error: Podfile not found in iosApp directory"
            exit 1
          fi

      - name: Build Framework
        run: ./gradlew :composeApp:assembleDebugAppleFrameworkForXcode

      - name: Build iOS App (Archive)
        run: |
          xcodebuild -project iosApp/iosApp.xcodeproj \
                     -scheme iosApp \
                     -sdk iphoneos \
                     -configuration Debug \
                     -archivePath $PWD/build/iosApp.xcarchive \
                     clean archive \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO

      - name: Prepare App for Sideloadly
        run: |
          mkdir -p build/Payload
          cp -r build/iosApp.xcarchive/Products/Applications/iosApp.app build/Payload/
          cd build
          zip -r PhimHay.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PhimHay-iOS-IPA
          path: build/PhimHay.ipa
